package view;



import dao.AlunoDao;
import dao.CursoDao;
import entidades.Aluno;
import entidades.Curso;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class EditorAluno extends javax.swing.JFrame {
    
    private AlunoDao alunoDao =  new AlunoDao();
    
    private boolean isEditar;

    private Curso curso;

    private int numeroSequencia;

    private ResourceBundle bundle = ResourceBundle.getBundle("Mensagens");

    private Map<Integer, Curso> mapCurso= new HashMap<>();

    private CursoEditor editor;

    public EditorAluno() {
        initComponents();
        setLocationRelativeTo( null );
        setDefaultCloseOperation(CursoEditor.DISPOSE_ON_CLOSE);
        this.editor = new CursoEditor();
        this.numeroSequencia = 1;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaContato = new javax.swing.JTable();
        botaoInserir = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoOK = new javax.swing.JButton();
        botaoFechar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaContato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Ementa"
            }
        ));
        jScrollPane1.setViewportView(tabelaContato);

        botaoInserir.setText("Inserir");
        botaoInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInserirActionPerformed(evt);
            }
        });

        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        botaoOK.setText("Ok");
        botaoOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOKActionPerformed(evt);
            }
        });

        botaoFechar.setText("Fechar");
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });

        jLabel4.setText("Seus Cursos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoExcluir)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoOK, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoFechar)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoInserir)
                    .addComponent(botaoEditar)
                    .addComponent(botaoExcluir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoOK)
                    .addComponent(botaoFechar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        if (JOptionPane.showConfirmDialog(null, bundle.getString(
                "AlunoEditor.ui.desejaFechar"), bundle.getString(
                        "AlunoEditor.ui.fechar"), JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_botaoFecharActionPerformed

//    public void envia(ClienteWindomPainel aThis) {
//        this.clienteWp = aThis;
//    }

    public void retorno(Curso curso) {
        this.curso = curso;
        populaTb();
    }
//
//    public void editar(Cliente cliente, ClienteWindomPainel clienteWp, ClienteDao clieteDao) {
//        textNome.setText(cliente.getNomeFantasia());
//        textCpf.setText(cliente.getCpf());
//        textCnpj.setText(cliente.getCnpj());
//        textRazaosocial.setText(cliente.getRazaoSocial());
//
//        this.clienteWp = clienteWp;
//        this.alunoDao = alunoDao;
//    }

    private void populaTb() {
//        DefaultTableModel model = (DefaultTableModel) tabelaContato.getModel();
//        mapCurso.put(numeroSequencia++, curso);
//        model.addRow(new String[]{
//            curso.getNome(), curso.getEmenta()});
    }
    
    private void botaoOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOKActionPerformed
        
//        if(textNome.getText().isEmpty() && textSenha.getText().isEmpty()){;
//            JOptionPane.showMessageDialog(null, "Digite o nome e a senha do aluno!");
//            return;
//        }
//        
//        Aluno aluno = new Aluno();
//        
//        aluno.setNome(textNome.getText());
//        aluno.setSenha(textSenha.getText());
//
//        if (mapCurso != null) {
//            List<Curso> cursos = new ArrayList<>();
//            for (Map.Entry<Integer, Curso> entry : mapCurso.entrySet()) {
//                cursos.add(entry.getValue());
//            }
//
//            aluno.setCursos(cursos);
//            CursoDao cursoDao = new CursoDao();
//            cursoDao.salvar(curso);
//        }
//        alunoDao.salvar(aluno);
//        
//        this.dispose();
        
    }//GEN-LAST:event_botaoOKActionPerformed

    private void botaoInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInserirActionPerformed
//        CursoEditor contatoEditor = new CursoEditor();
//        contatoEditor.setVisible(true);
//        contatoEditor.envia(this);

    }//GEN-LAST:event_botaoInserirActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
//        excluir();

    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void excluir() {
//        int linha = tabelaContato.getSelectedRow();
//        DefaultTableModel model = (DefaultTableModel) tabelaContato.getModel();
//        model.removeRow(linha);
    }

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
//        CursoEditor editor = new CursoEditor();
//        editor.setVisible(true);
//        int linha = tabelaContato.getSelectedRow();
//
//        int l = ++linha;
//        Curso curso = mapCurso.get(l);
//        mapCurso.remove(l);
//        editor.editar(curso, this);
//        Curso contatoNovo = new Curso();
//        contatoNovo.setNome(this.curso.getNome());
//        contatoNovo.setEmenta(this.curso.getEmenta());
//
//        if (curso != this.curso) {
//            mapCurso.put(l, this.curso);
//        }
//
//        excluir();
    }//GEN-LAST:event_botaoEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JButton botaoInserir;
    private javax.swing.JButton botaoOK;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaContato;
    // End of variables declaration//GEN-END:variables
}
